---
- name: install wget
  yum: name=wget state=present

- name: install java
  yum: name=java state=present

- name: wget spring-xd
  command: "wget -nc https://repo.spring.io/libs-release-local/org/springframework/xd/spring-xd/1.3.1.RELEASE/spring-xd-1.3.1.RELEASE-1.noarch.rpm"


# Install spring-xd-1.3.1.RELEASE-1.noarch.rpm
#- name: "install spring-xd"
#  command: "yum install spring-xd-1.3.1.RELEASE-1.noarch.rpm"

- name: "install spring-xd"
  yum: name=spring-xd-1.3.1.RELEASE-1.noarch.rpm state=present

# Verify Pivotal's RPM repo is present so we can install Spring-XD
#- yum: name=app-suite-repo state=present

# replace the lines that make you accept the EULA so it auto accepts
#- replace: dest=/etc/pivotal/pivotal-eula-acceptance.sh regexp="^(\s+less .*)"      replace='#\1'
#- replace: dest=/etc/pivotal/pivotal-eula-acceptance.sh regexp="^(\s+printf.*)"     replace='#\1'
#- replace: dest=/etc/pivotal/pivotal-eula-acceptance.sh regexp="^(\s+read reply.*)" replace='#\1'
#- lineinfile: dest=/etc/pivotal/pivotal-eula-acceptance.sh line="      reply=yes" insertafter=".*read reply.*"

#- name: run pivotal EULA to accept it automatically to get additional yum repos for spring-xd
#  command: /etc/pivotal/pivotal-eula-acceptance.sh

#- name: install spring-xd
#  yum: name=spring-xd state=present

# Template spring-xd servers.yml file
- name: template spring-xd servers.yml
  template: src=servers.yml.j2 dest=/opt/pivotal/spring-xd-1.3.1.RELEASE/xd/config/servers.yml
  tags:
    - template

