# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "z1" do |z1|
    z1.vm.box = "bento/centos-6.7"
    z1.vm.hostname = 'z1'
    z1.vm.network "forwarded_port", guest: 22, host: 2221, id: "ssh"
    z1.vm.network "private_network", ip: "192.168.100.221"
    z1.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 1
    end
  end

  config.vm.define "z2" do |z2|
    z2.vm.box = "bento/centos-6.7"
    z2.vm.hostname = 'z2'
    z2.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
    z2.vm.network "private_network", ip: "192.168.100.222"
    z2.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 1
    end

  end

  config.vm.define "z3" do |z3|
    z3.vm.box = "bento/centos-6.7"
    z3.vm.hostname = 'z3'
    z3.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"
    z3.vm.network "private_network", ip: "192.168.100.223"
    z3.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 1
    end
  end

  config.vm.define "pgsql" do |pgsql|
    pgsql.vm.box = "bento/centos-6.7"
    pgsql.vm.hostname = 'pgsql'
    pgsql.vm.network "forwarded_port", guest: 22, host: 2224, id: "ssh"
    pgsql.vm.network "private_network", ip: "192.168.100.224"
    pgsql.vm.provider :virtualbox do |v|
      v.memory = 512
      v.cpus = 1
    end
  end

  config.vm.define "redis" do |redis|
    redis.vm.box = "bento/centos-6.7"
    redis.vm.hostname = 'redis'
    redis.vm.network "forwarded_port", guest: 22, host: 2225, id: "ssh"
    redis.vm.network "private_network", ip: "192.168.100.225"
    redis.vm.provider :virtualbox do |v|
      v.memory = 256
      v.cpus = 1
    end
  end

  config.vm.define "s1" do |s1|
    s1.vm.box = "bento/centos-6.7"
    s1.vm.hostname = 's1'
    s1.vm.network "forwarded_port", guest: 22, host: 2226, id: "ssh"
    s1.vm.network "private_network", ip: "192.168.100.226"
    s1.vm.provider :virtualbox do |v|
      v.memory = 256
      v.cpus = 1
    end
  end

  config.vm.define "s2" do |s2|
    s2.vm.box = "bento/centos-6.7"
    s2.vm.hostname = 's2'
    s2.vm.network "forwarded_port", guest: 22, host: 2227, id: "ssh"
    s2.vm.network "private_network", ip: "192.168.100.227"
    s2.vm.provider :virtualbox do |v|
      v.memory = 256
      v.cpus = 1
    end
  end

end


ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
