# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

base_box="centos/7"
memory=512
cpus=1

nodes = [
  {
  name:'z1',
  ip:'192.168.100.221'
  },
  {
  name:'z2',
  ip:'192.168.100.222'
  },
  {
  name:'z3',
  ip:'192.168.100.223'
  },
  {
  name:'s1',
  ip:'192.168.100.226'
  },
  {
  name:'s2',
  ip:'192.168.100.227'
  },
  {
  name:'pgsql',
  ip:'192.168.100.224'
  },
  {
  name:'redis',
  ip:'192.168.100.225'
  }
]


Vagrant.configure(2) do |config|

  nodes.each do |i|
    config.vm.define "#{i[:name]}" do |node|
      node.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
                   echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
                   SHELL
      end
      node.vm.box = base_box
      node.vm.hostname = "#{i[:name]}"
      node.vm.network "private_network", ip: "#{i[:ip]}"
      node.vm.provider :virtualbox do |v|
        v.memory = memory
        v.cpus = cpus
      end
    end
  end

end


ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
