---
# tasks file for spring-xd-docker


- name: redis container
  docker:
    name: redis
    image: redis
    state: reloaded
    expose:
      - "{{ redis_expose }}"
    ports:
      - "{{ redis_docker_port }}"
    docker_api_version: "{{ docker_server_api_version }}"

- name: hsqldb container
  docker:
    name: hsqldb
    image: springxd/hsqldb
    state: reloaded
    expose:
      - "{{ hsqldb_expose }}"
    ports:
      - "{{ hsqldb_docker_port }}"
    docker_api_version: "{{ docker_server_api_version }}"

- name: zookeeper container
  docker:
    name: zookeeper
    image: springxd/zookeeper
    state: reloaded
    expose:
      - "{{ zookeeper_expose }}"
    ports:
      - "{{ zookeeper_docker_port }}"
    docker_api_version: "{{ docker_server_api_version }}"


- name: springxd container container
  docker:
    name: springxd_container1
    image: springxd/container
    state: reloaded
    links:
      - "redis:redis"
      - "zookeeper:zookeeper"
      - "hsqldb:hsqldb"
    docker_api_version: "{{ docker_server_api_version }}"

- name: springxd admin
  docker:
    name: springxd_admin
    image: springxd/admin
    state: reloaded
    expose:
      - "{{ springxd_admin_expose }}"
    ports:
      - "{{ springxd_admin_docker_port }}"
    links:
      - "redis:redis"
      - "zookeeper:zookeeper"
      - "hsqldb:hsqldb"
    docker_api_version: "{{ docker_server_api_version }}"
