---
# tasks file for spring-xd-docker


- name: redis container
  docker:
    name: redis
    image: redis
    state: reloaded
    expose:
      - "{{ redis_expose }}"
    ports:
      - "{{ redis_port }}"
    docker_api_version: "{{ docker_server_api_version }}"

- name: hsqldb container
  docker:
    name: hsqldb
    image: springxd/hsqldb
    state: reloaded
    expose:
      - "{{ hsqldb_expose }}"
    ports:
      - "{{ hsqldb_port }}"
    docker_api_version: "{{ docker_server_api_version }}"

- name: zookeeper container
  docker:
    name: zookeeper
    image: springxd/zookeeper
    state: reloaded
    expose:
      - "{{ zookeeper_expose }}"
    ports:
      - "{{ zookeeper_port }}"
    docker_api_version: "{{ docker_server_api_version }}"
