- name: waiting after restart xd
  shell: while true; do sudo netstat -tulpn | grep 9393 && break || sleep 1; done

- name: deploy.cmdfile
  template: src=deploy.cmdfile.j2 dest=~/deploy.cmdfile

- name: "deploy stream"
  shell: xd-shell --cmdfile ~/deploy.cmdfile
