- name: waiting after restart xd
  shell: while true; do sudo netstat -tulpn | grep 9393 && break || sleep 1; done

- name: destroy.cmdfile
  template: src=destroy.cmdfile.j2 dest=~/destroy.cmdfile


- name: "destroy stream"
  shell: xd-shell --cmdfile ~/destroy.cmdfile

